### PR TITLE
Composer updates

### PR DESCRIPTION
**Pull request by pensiero**
- Updated required Zend Framework package in order to do not load the entitire framework, but only what's needed
- Moved the required package from `required-dev` to `required` (`zf2-route-inheritance` it's not useful if not applied to the `zend-mvc` package)
- Committed `composer.lock` (needed for `composer install` process)

### CODE REVIEW

**Comment by pensiero** [comment]
@hickeroar I thing these changes could lighten the vendor library of all the users that are using `zf2-route-inheritance`

**Comment by hickeroar** [comment]
@pensiero I haven't used ZF since about the time your last PR came through in sept 2015. I'm going to assume these are good, but for the record, if anyone else is using this and this causes problems, they will just have to chime in. :) My only concern is dropping support for v2.3, but I suppose people should be keeping their apps up to date.

**Comment by pensiero** [comment]
Thanks @hickeroar 
You can simply create a new release (0.3.0). In this way, if someone is using the `0.2.*` or `^0.2` will not be affected. 

Thanks again

**Comment by hickeroar** [comment]
Done. :) Thanks for the updates.

**Comment by pensiero** [comment]
Thank you!

**Pull request merged**
